SUPABASE_URL = "https://tossxgtjyaydtshmoskk.supabase.co"
SUPABASE_KEY = "sb_publishable_tGrRzVpsoiS1vQftc0zyMg_3rK0m4Vs"
OPENROUTER_API_KEY = "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"